version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: inline
      timeout: 300
      runas: root
      commands:
        - docker rm -f simple-java-maven-app || true  # Stop and remove old container if it exists

  AfterInstall:
    - location: inline
      timeout: 300
      runas: root
      commands:
        - docker pull zangetsu203/simple-java-maven-app:latest  # Pull the latest image from Docker Hub
        - docker run -d --name simple-java-maven-app zangetsu203/simple-java-maven-app:latest  # Run container
