version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: inline
      timeout: 300
      runas: root
      commands:
        - docker rm -f my-app-container || true

  AfterInstall:
    - location: inline
      timeout: 300
      runas: root
      commands:
        - docker build -t my-app /home/ec2-user/my-app/
        - docker run -d --name my-app-container -p 8080:8080 my-app
