sonar.projectKey=java
sonar.projectName=java
# sonar.projectVersion=1.0
# sonar.projectBaseDir=.

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
# sonar.junit.reportPaths=target/surefire-reports
# sonar.java.coveragePlugin=jacoco
sonar.sourceEncoding=UTF-8
sonar.host.url=http://3.110.117.91:9000