def gv 

pipeline {
    agent any
    parameters {
        string(name: 'VERSION', defaultValue: "", description: 'version to deploy on production')
    }
    tools {
        maven 'maven-3.99'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('init build') {
            steps {
                script {
                    gv = load "./scripts/script.groovy"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    gv.buildApp()
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    gv.testApp()
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage( 'Build image'){
            steps {
                script {
                    gv.buildAndPushDockerImage()
                }
            }
        }
        
        stage('Deliver') { 
            steps {
                script {
                    gv.deliverApp()    
                }      
            }
        }
    }
}
