pipeline {
    
    environment {
        
        registry = "bopporgo/boppururepo"
        registryCredential = 'dockerhub'
        dockerImage = ''
        
    }
    agent {
        docker {
            image 'maven:3-alpine'
           args '-u root'
         
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'dockerinfo'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('build') {
            steps {
                agent {docker 
                 {
                script {
                dockerImage =  docker.build registry + ":$BUILD_NUMBER" 
            }
        }
    }

        stage ('deploy') {
            
            steps {
                script {
                    
           docker.with registry ('',registryCredential) { 

               dockerImage.push()
    
                    }
                }
            }
    }
  }
}
