pipeline {
    agent any 
    tools {
        maven 'maven-3.9'
    }
    stages {
        stage("build jar") {
            steps {
                script {
                    echo " building the jarfile"
                    sh 'mvn package'
                }
            }
        }

        stage("build image") {
            steps {
                script {
                    echo " building the image ..."
                    withCredentials([usernamePassword(credentialsId:'docker-hub', usernameVariable: 'USERNAME', passwordVariable:'PASSWORD')]){
                        sh 'docker build -t walidelbir/devops-bootcamp:jma-2.0 .'
                        sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                        sh 'docker push walidelbir/devops-bootcamp:jma-2.0'
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    echo "deploying the application ... "
                }
            }
        }
    }
}
