pipeline {
    agent any
    tools {
        maven 'maven-3.5.2'
        jdk 'jdk-1.8.0_162'
    }
    stages {
        stage('Example') {
            input {
                message "Create a Release?"
                ok "GO"
                parameters {
                    string(name: 'Version', description: 'Release version (e.g. 2.0.0)')
                    string(name: 'TagName', description: 'Name of Tag (e.g. 2.0.0)')
                }
            }
            steps {
                echo "Going to create release ${Version} with ${TagName}"
            }
        }
        stage('Clean') {
            steps {
                sh 'mvn -B -ff -V -U clean'
            }
        }
        stage('Set Version') {
            steps {
                sh 'mvn -B -ff -V -U versions:set -DnewVersion'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -fae -V -U install'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}