name: Dockerfile Scan

on:
  push:
    branches:
      - master

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Install Snyk
      #   run: npm install -g snyk

      # - name: Authenticate Snyk
      #   run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Dockerfile Scan
        run: snyk test --file=Dockerfile
        # env:
        #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Build Docker image
        run: docker build -t my-app:latest .

     
