name: Test writing pipeline
on:
  push:
    branches:
      - master

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '21'
            cache: maven
      - name: list downloaded files    
        run: | 
          mvn --version
          ls
          pwd
      - name: Build application
        run: mvn clean package
      - name: Show JAR file
        run: ls target/*.jar
          
      - name: Run 2nd test
        run: mvn clean verify
        
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
