name: Test writing pipeline
on:
  push:
    branches:
      - master

jobs:
  test-my-writing:
    runs-on: ubuntu-latest

    steps:
      - name: user name
        run: whoami
      - name: print working directory
        run: pwd
      - name: print OS release
        run: cat /etc/os-release
      - name: print my signature
        run: echo "by underbis on 5-31-2026"
        
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '17'
            cache: maven
      - name: list downloaded files    
        run: | 
          ls
          pwd
      - name: Build application
        run: |
          mvn clean package
          ls target/*.jar
      - name: Run test
        run: mvn clean verify
